const characters = [
    { name: 'Traveler (Anemo)', element: 'anemo' },
    { name: 'Traveler (Geo)', element: 'geo' },
    { name: 'Traveler (Electro)', element: 'electro' },
    { name: 'Traveler (Dendro)', element: 'dendro' },
    { name: 'Traveler (Hydro)', element: 'hydro' },
    { name: 'Amber', element: 'pyro' },
    { name: 'Kaeya', element: 'cryo' },
    { name: 'Lisa', element: 'electro' },
    { name: 'Barbara', element: 'hydro' },
    { name: 'Razor', element: 'electro' },
    { name: 'Xiangling', element: 'pyro' },
    { name: 'Beidou', element: 'electro' },
    { name: 'Xingqiu', element: 'hydro' },
    { name: 'Ningguang', element: 'geo' },
    { name: 'Fischl', element: 'electro' },
    { name: 'Bennett', element: 'pyro' },
    { name: 'Noelle', element: 'geo' },
    { name: 'Chongyun', element: 'cryo' },
    { name: 'Sucrose', element: 'anemo' },
    { name: 'Jean', element: 'anemo' },
    { name: 'Diluc', element: 'pyro' },
    { name: 'Qiqi', element: 'cryo' },
    { name: 'Mona', element: 'hydro' },
    { name: 'Keqing', element: 'electro' },
    { name: 'Venti', element: 'anemo' },
    { name: 'Klee', element: 'pyro' },
    { name: 'Diona', element: 'cryo' },
    { name: 'Tartaglia', element: 'hydro' },
    { name: 'Xinyan', element: 'pyro' },
    { name: 'Zhongli', element: 'geo' },
    { name: 'Albedo', element: 'geo' },
    { name: 'Ganyu', element: 'cryo' },
    { name: 'Xiao', element: 'anemo' },
    { name: 'Hu Tao', element: 'pyro' },
    { name: 'Rosaria', element: 'cryo' },
    { name: 'Yanfei', element: 'pyro' },
    { name: 'Eula', element: 'cryo' },
    { name: 'Kaedehara Kazuha', element: 'anemo' },
    { name: 'Kamisato Ayaka', element: 'cryo' },
    { name: 'Sayu', element: 'anemo' },
    { name: 'Yoimiya', element: 'pyro' },
    { name: 'Kujou Sara', element: 'electro' },
    { name: 'Aloy', element: 'cryo' },
    { name: 'Raiden Shogun', element: 'electro' },
    { name: 'Sangonomiya Kokomi', element: 'hydro' },
    { name: 'Thoma', element: 'pyro' },
    { name: 'Gorou', element: 'geo' },
    { name: 'Arataki Itto', element: 'geo' },
    { name: 'Yun jin', element: 'geo' },
    { name: 'Shenhe', element: 'cryo' },
    { name: 'Yae Miko', element: 'electro' },
    { name: 'Kamisato Ayato', element: 'hydro' },
    { name: 'Yelan', element: 'hydro' },
    { name: 'Kuki Shinobu', element: 'electro' },
    { name: 'Shikanoin Heizou', element: 'anemo' },
    { name: 'Collei', element: 'dendro' },
    { name: 'Tighnari', element: 'dendro' },
    { name: 'Dori', element: 'electro' },
    { name: 'Candace', element: 'hydro' },
    { name: 'Cyno', element: 'electro' },
    { name: 'Nilou', element: 'hydro' },
    { name: 'Nahida', element: 'dendro' },
    { name: 'Layla', element: 'cryo' },
    { name: 'Faruzan', element: 'anemo' },
    { name: 'Wanderer', element: 'anemo' },
    { name: 'Yaoyao', element: 'dendro' },
    { name: 'Alhaitham', element: 'dendro' },
    { name: 'Dehya', element: 'pyro' },
    { name: 'Mika', element: 'cryo' },
    { name: 'Kaveh', element: 'dendro' },
    { name: 'Baizhu', element: 'dendro' },
    { name: 'Kirara', element: 'dendro' },
    { name: 'Lynette', element: 'anemo' },
    { name: 'Lyney', element: 'pyro' },
    { name: 'Freminet', element: 'cryo' },
    { name: 'Neuvillette', element: 'hydro' },
    { name: 'Wriothesley', element: 'cryo' },
    { name: 'Charlotte', element: 'cryo' },
    { name: 'Furina', element: 'hydro' },
    { name: 'Navia', element: 'geo' },
    { name: 'Chevreuse', element: 'pyro' },
    { name: 'Gaming', element: 'pyro' },
    { name: 'Xianyun', element: 'anemo' },
    { name: 'Chiori', element: 'geo' },
];

const elements = {
    pyro: '1236278501594759178',
    hydro: '1236278499334029332',
    anemo: '1236278490123341864',
    electro: '1236278494497869875',
    dendro: '1236278496997675088',
    cryo: '1236278503528464434',
    geo: '1236278492363096146',
};

const characterelements = characters.reduce((acc, { name, element }) => {
    acc[name] = elements[element];
    return acc;
}, {});

module.exports = { characters, characterelements };
